name: Terraform Lint

on:
  pull_request:
    paths:
      - '**.tf'
      - '**.tfvars'
      - '.github/workflows/terraform-lint.yml'

permissions:
  contents: read
  pull-requests: write # Needed for commenting on PRs

jobs:
  tflint:
    name: TFLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.46.1

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        id: tflint
        run: |
          tflint -f json > tflint_results.json || echo "TFLint found issues"
          tflint -f compact
